// Fresh internet-sourced product-only visual library.
// 0: listing + hero; 1: video poster; 2: operational/GIF preview;
// 3-5: detail gallery; 6: related-product card.
// Every selected source file is unique across all product and service entries.
export const UNIQUE_PRODUCT_MEDIA: Record<string, string[]> = {
  "basic-magnetic-gps": [
    "/media/products-fresh/basic-magnetic-gps-1.jpg",
    "/media/products-fresh/basic-magnetic-gps-2.png",
    "/media/products-fresh/basic-magnetic-gps-3.png",
    "/media/products-fresh/basic-magnetic-gps-4.jpg",
    "/media/products-fresh/basic-magnetic-gps-6.jpg",
    "/media/products-fresh/basic-magnetic-gps-7.png",
    "/media/products-fresh/basic-magnetic-gps-8.png",
  ],
  "ais140-gps-hardware": [
    "/media/products-fresh/ais140-gps-hardware-1.webp",
    "/media/products-fresh/ais140-gps-hardware-2.jpg",
    "/media/products-fresh/ais140-gps-hardware-3.png",
    "/media/products-fresh/ais140-gps-hardware-4.png",
    "/media/products-fresh/ais140-gps-hardware-7.png",
    "/media/products-fresh/ais140-gps-hardware-8.jpg",
    "/media/products-fresh/ais140-gps-hardware-11.webp",
  ],
  "video-telematics-solutions": [
    "/media/products-fresh/video-telematics-solutions-1.jpg",
    "/media/products-fresh/video-telematics-solutions-2.webp",
    "/media/products-fresh/video-telematics-solutions-3.png",
    "/media/products-fresh/video-telematics-solutions-4.jpg",
    "/media/products-fresh/video-telematics-solutions-5.jpg",
    "/media/products-fresh/video-telematics-solutions-6.jpg",
    "/media/products-fresh/video-telematics-solutions-7.jpg",
  ],
  "personal-pet-wallet-tracker": [
    "/media/products-fresh/personal-pet-wallet-tracker-1.jpg",
    "/media/products-fresh/personal-pet-wallet-tracker-2.jpg",
    "/media/products-fresh/personal-pet-wallet-tracker-3.jpeg",
    "/media/products-fresh/personal-pet-wallet-tracker-4.jpg",
    "/media/products-fresh/personal-pet-wallet-tracker-5.jpg",
    "/media/products-fresh/personal-pet-wallet-tracker-6.jpg",
    "/media/products-fresh/personal-pet-wallet-tracker-8.jpg",
  ],
  "fatigue-sensor-solutions": [
    "/media/products-fresh/fatigue-sensor-solutions-1.jpg",
    "/media/products-fresh/fatigue-sensor-solutions-2.jpg",
    "/media/products-fresh/fatigue-sensor-solutions-3.jpeg",
    "/media/products-fresh/fatigue-sensor-solutions-4.jpg",
    "/media/products-fresh/fatigue-sensor-solutions-5.jpg",
    "/media/products-fresh/fatigue-sensor-solutions-6.jpg",
    "/media/products-fresh/fatigue-sensor-solutions-8.jpg",
  ],
  "gps-dash-camera": [
    "/media/products-fresh/gps-dash-camera-1.png",
    "/media/products-fresh/gps-dash-camera-3.jpg",
    "/media/products-fresh/gps-dash-camera-5.jpg",
    "/media/products-fresh/gps-dash-camera-6.webp",
    "/media/products-fresh/gps-dash-camera-8.jpg",
    "/media/products-fresh/gps-dash-camera-9.png",
    "/media/products-fresh/gps-dash-camera-11.webp",
  ],
  "gps-digital-lock-valuable-transport": [
    "/media/products-fresh/gps-digital-lock-valuable-transport-1.jpg",
    "/media/products-fresh/gps-digital-lock-valuable-transport-2.jpg",
    "/media/products-fresh/gps-digital-lock-valuable-transport-3.jpg",
    "/media/products-fresh/gps-digital-lock-valuable-transport-4.jpeg",
    "/media/products-fresh/gps-digital-lock-valuable-transport-5.webp",
    "/media/products-fresh/gps-digital-lock-valuable-transport-6.webp",
    "/media/products-fresh/gps-digital-lock-valuable-transport-8.webp",
  ],
  "iot-hardware-ev-vehicles-batteries": [
    "/media/products-fresh/iot-hardware-ev-vehicles-batteries-1.jpg",
    "/media/products-fresh/iot-hardware-ev-vehicles-batteries-2.jpg",
    "/media/products-fresh/iot-hardware-ev-vehicles-batteries-3.jpg",
    "/media/products-fresh/iot-hardware-ev-vehicles-batteries-4.jpg",
    "/media/products-fresh/iot-hardware-ev-vehicles-batteries-6.png",
    "/media/products-fresh/iot-hardware-ev-vehicles-batteries-9.jpg",
    "/media/products-fresh/iot-hardware-ev-vehicles-batteries-10.webp",
  ],
  "cctv-dash-cams-security-surveillance": [
    "/media/products-fresh/cctv-dash-cams-security-surveillance-1.jpg",
    "/media/products-fresh/cctv-dash-cams-security-surveillance-2.jpg",
    "/media/products-fresh/cctv-dash-cams-security-surveillance-3.jpg",
    "/media/products-fresh/cctv-dash-cams-security-surveillance-4.jpg",
    "/media/products-fresh/cctv-dash-cams-security-surveillance-5.jpg",
    "/media/products-fresh/cctv-dash-cams-security-surveillance-6.jpg",
    "/media/products-fresh/cctv-dash-cams-security-surveillance-7.jpg",
  ],
  "cable-wire-security-seal-logistics": [
    "/media/products-fresh/cable-wire-security-seal-logistics-1.jpg",
    "/media/products-fresh/cable-wire-security-seal-logistics-2.jpg",
    "/media/products-fresh/cable-wire-security-seal-logistics-3.jpg",
    "/media/products-fresh/cable-wire-security-seal-logistics-4.png",
    "/media/products-fresh/cable-wire-security-seal-logistics-5.jpg",
    "/media/products-fresh/cable-wire-security-seal-logistics-6.jpg",
    "/media/products-fresh/cable-wire-security-seal-logistics-7.jpg",
  ],
  "container-seal-logistics-transportation": [
    "/media/products-fresh/container-seal-logistics-transportation-1.jpg",
    "/media/products-fresh/container-seal-logistics-transportation-2.jpg",
    "/media/products-fresh/container-seal-logistics-transportation-3.jpg",
    "/media/products-fresh/container-seal-logistics-transportation-4.png",
    "/media/products-fresh/container-seal-logistics-transportation-5.jpg",
    "/media/products-fresh/container-seal-logistics-transportation-6.jpg",
    "/media/products-fresh/container-seal-logistics-transportation-7.jpg",
  ],
  "smart-id-cards": [
    "/media/products-fresh/smart-id-cards-1.webp",
    "/media/products-fresh/smart-id-cards-2.jpg",
    "/media/products-fresh/smart-id-cards-3.webp",
    "/media/products-fresh/smart-id-cards-4.jpg",
    "/media/products-fresh/smart-id-cards-5.png",
    "/media/products-fresh/smart-id-cards-6.jpg",
    "/media/products-fresh/smart-id-cards-7.webp",
  ],
  "pet-tracking-gps": [
    "/media/products-fresh/pet-tracking-gps-1.png",
    "/media/products-fresh/pet-tracking-gps-2.jpg",
    "/media/products-fresh/pet-tracking-gps-3.jpg",
    "/media/products-fresh/pet-tracking-gps-4.jpg",
    "/media/products-fresh/pet-tracking-gps-5.jpg",
    "/media/products-fresh/pet-tracking-gps-7.jpg",
    "/media/products-fresh/pet-tracking-gps-9.jpg",
  ],
  "fleet-management-dashboard": [
    "/media/products-fresh/fleet-management-dashboard-1.webp",
    "/media/products-fresh/fleet-management-dashboard-2.webp",
    "/media/products-fresh/fleet-management-dashboard-3.png",
    "/media/products-fresh/fleet-management-dashboard-4.png",
    "/media/products-fresh/fleet-management-dashboard-5.png",
    "/media/products-fresh/fleet-management-dashboard-6.jpg",
    "/media/products-fresh/fleet-management-dashboard-7.webp",
  ],
  "bizeye-fleet-employee-asset-tracking": [
    "/media/products-fresh/bizeye-fleet-employee-asset-tracking-1.webp",
    "/media/products-fresh/bizeye-fleet-employee-asset-tracking-2.png",
    "/media/products-fresh/bizeye-fleet-employee-asset-tracking-3.png",
    "/media/products-fresh/bizeye-fleet-employee-asset-tracking-4.jpg",
    "/media/products-fresh/bizeye-fleet-employee-asset-tracking-5.png",
    "/media/products-fresh/bizeye-fleet-employee-asset-tracking-6.png",
    "/media/products-fresh/bizeye-fleet-employee-asset-tracking-7.png",
  ],
  "spark-iot-ev-battery-health-monitoring": [
    "/media/products-fresh/spark-iot-ev-battery-health-monitoring-1.png",
    "/media/products-fresh/spark-iot-ev-battery-health-monitoring-2.jpg",
    "/media/products-fresh/spark-iot-ev-battery-health-monitoring-3.jpg",
    "/media/products-fresh/spark-iot-ev-battery-health-monitoring-4.png",
    "/media/products-fresh/spark-iot-ev-battery-health-monitoring-5.jpg",
    "/media/products-fresh/spark-iot-ev-battery-health-monitoring-6.jpg",
    "/media/products-fresh/spark-iot-ev-battery-health-monitoring-8.png",
  ],
  "event-management-application": [
    "/media/products-fresh/event-management-application-1.png",
    "/media/products-fresh/event-management-application-2.png",
    "/media/products-fresh/event-management-application-3.png",
    "/media/products-fresh/event-management-application-4.png",
    "/media/products-fresh/event-management-application-5.png",
    "/media/products-fresh/event-management-application-6.jpg",
    "/media/products-fresh/event-management-application-7.jpg",
  ],
  "saphal-agri-procurement-handling-logistics": [
    "/media/products-fresh/saphal-agri-procurement-handling-logistics-1.jpg",
    "/media/products-fresh/saphal-agri-procurement-handling-logistics-2.png",
    "/media/products-fresh/saphal-agri-procurement-handling-logistics-3.png",
    "/media/products-fresh/saphal-agri-procurement-handling-logistics-4.webp",
    "/media/products-fresh/saphal-agri-procurement-handling-logistics-5.png",
    "/media/products-fresh/saphal-agri-procurement-handling-logistics-6.png",
    "/media/products-fresh/saphal-agri-procurement-handling-logistics-7.jpg",
  ],
  "workflow-tracer-operational-tracing": [
    "/media/products-fresh/workflow-tracer-operational-tracing-1.png",
    "/media/products-fresh/workflow-tracer-operational-tracing-2.jpg",
    "/media/products-fresh/workflow-tracer-operational-tracing-3.png",
    "/media/products-fresh/workflow-tracer-operational-tracing-4.png",
    "/media/products-fresh/workflow-tracer-operational-tracing-5.png",
    "/media/products-fresh/workflow-tracer-operational-tracing-6.jpg",
    "/media/products-fresh/workflow-tracer-operational-tracing-7.jpg",
  ],
  "whatsapp-appointment-order-management": [
    "/media/products-fresh/whatsapp-appointment-order-management-1.jpg",
    "/media/products-fresh/whatsapp-appointment-order-management-2.webp",
    "/media/products-fresh/whatsapp-appointment-order-management-3.png",
    "/media/products-fresh/whatsapp-appointment-order-management-4.webp",
    "/media/products-fresh/whatsapp-appointment-order-management-5.webp",
    "/media/products-fresh/whatsapp-appointment-order-management-6.png",
    "/media/products-fresh/whatsapp-appointment-order-management-7.png",
  ],
  "mobile-tracking-app": [
    "/media/products-fresh/mobile-tracking-app-1.png",
    "/media/products-fresh/mobile-tracking-app-2.webp",
    "/media/products-fresh/mobile-tracking-app-3.png",
    "/media/products-fresh/mobile-tracking-app-4.png",
    "/media/products-fresh/mobile-tracking-app-5.png",
    "/media/products-fresh/mobile-tracking-app-6.webp",
    "/media/products-fresh/mobile-tracking-app-7.png",
  ],
  "enterprise-api-gateway": [
    "/media/products-fresh/enterprise-api-gateway-1.png",
    "/media/products-fresh/enterprise-api-gateway-2.png",
    "/media/products-fresh/enterprise-api-gateway-3.jpg",
    "/media/products-fresh/enterprise-api-gateway-4.png",
    "/media/products-fresh/enterprise-api-gateway-5.png",
    "/media/products-fresh/enterprise-api-gateway-6.webp",
    "/media/products-fresh/enterprise-api-gateway-7.png",
  ],
  "smart-geofencing-engine": [
    "/media/products-fresh/smart-geofencing-engine-1.jpeg",
    "/media/products-fresh/smart-geofencing-engine-2.jpg",
    "/media/products-fresh/smart-geofencing-engine-3.webp",
    "/media/products-fresh/smart-geofencing-engine-4.png",
    "/media/products-fresh/smart-geofencing-engine-5.png",
    "/media/products-fresh/smart-geofencing-engine-6.jpg",
    "/media/products-fresh/smart-geofencing-engine-8.jpg",
  ],
  "driver-behavior-ai": [
    "/media/products-fresh/driver-behavior-ai-1.png",
    "/media/products-fresh/driver-behavior-ai-2.png",
    "/media/products-fresh/driver-behavior-ai-3.png",
    "/media/products-fresh/driver-behavior-ai-4.jpg",
    "/media/products-fresh/driver-behavior-ai-5.webp",
    "/media/products-fresh/driver-behavior-ai-6.webp",
    "/media/products-fresh/driver-behavior-ai-7.png",
  ],
  "predictive-maintenance-portal": [
    "/media/products-fresh/predictive-maintenance-portal-1.webp",
    "/media/products-fresh/predictive-maintenance-portal-2.jpg",
    "/media/products-fresh/predictive-maintenance-portal-3.jpg",
    "/media/products-fresh/predictive-maintenance-portal-4.png",
    "/media/products-fresh/predictive-maintenance-portal-5.jpg",
    "/media/products-fresh/predictive-maintenance-portal-6.jpg",
    "/media/products-fresh/predictive-maintenance-portal-7.jpg",
  ],
};

export const getUniqueProductMedia = (id: string, fallback: string[]) =>
  UNIQUE_PRODUCT_MEDIA[id] ?? fallback;
